[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_unflags = -std=gnu++11
build_flags = -std=gnu++17
monitor_filters = log2file
lib_deps =
    knolleary/PubSubClient@^2.8
#    madhephaestus/ESP32Encoder@^0.10.2
